---
fontsize: 12pt
geometry: margin=0.50in
header-includes:
   - \usepackage{longtable}
   - \usepackage[singlelinecheck=false]{caption}
   - \usepackage{titlesec}
   - \usepackage{array}
   - \usepackage{makecell}
   - \usepackage{booktabs}
   - \usepackage{colortbl}
   - \usepackage{xunicode}
   - \usepackage{float}
   - \usepackage{pdflscape}
   - \newcommand{\blandscape}{\begin{landscape}}
   - \newcommand{\elandscape}{\end{landscape}}
output:
  pdf_document:
    toc: false
    keep_tex: no
    latex_engine: xelatex
---

```{r tab, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(knitr)
library(dplyr)
library(kableExtra)
config <- yaml::read_yaml('myGOI.yml')

caption <- ''
tab <- tibble(class = c('Depleted (D)', 'Enriched (E)', 'Abundant (A)', 'Longitudinal (L)'),
              desc = c('Depleted genes show a significant decrease (p $\\leq$ 0.05) in integration frequency at later time points.',
                       'Enriched genes show a significant increase (p < 0.05) in integration frequency at later time points.',
                       'Abundant genes are genes associated with the top 1\\% of clonal abundance estimates at later time points.',
                       paste0('Longitudinal genes are genes with $\\geq$ ', config$longitudinal_minNumSites, ' unique integrations from $\\geq$ ',                                         config$longitudinal_minNumSubjects, ' patients recovered $\\geq$ ', config$longitudinal_minTimeDays, ' days post-transduction.')))

kable(tab, "latex", align="rl", linesep = "", booktabs=T, escape = F, col.names = NULL, caption = caption) %>%
  kable_styling(latex_options = c("hold_position"), font_size = 9)
```


```{r Table2_legend, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
caption <- ''
tab <- tibble(class = c('gene', 'subjects', 'earlyCount', 'lateCount', 'percentChange', 'pVal', 'pVal.adj', 'oncoGene', 'categories'),
              desc = c('Gene symbol.',
                       'Total number of subjects with an integration near gene.',
                        paste0('Number of integration sites recovered from earlier time points ($\\leq$ ', config$earlyVsLateCutoffDays, ' days).'),
                        paste0('Number of integration sites recovered from later time points (> ', config$earlyVsLateCutoffDays, ' days).'),
                        paste0('Percent increase in integration frequency compared to earlier time period (>', config$earlyVsLateCutoffDays, ' days).'),
                        "p-value from Fisher's Exact test.",
                        "BH corrected p-value from Fisher's Exact test.",
                        "Gene is found in a broad lists of oncogenes.",
                        "DEAL categories associated with gene."))

kable(tab, "latex", align="rl", linesep = "", booktabs=T, escape = F, col.names = NULL, caption = caption) %>%
  kable_styling(latex_options = c("hold_position"), font_size = 10)
```


```{r xxx, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
caption <- ''
tab <- tibble(class = c('gene', 'subjects', 'lateCount', 'maxAbund', 'maxRelAbund', 'oncoGene', 'categories'),
              desc = c('Gene symbol.',
                       'Total number of subjects with an integration near gene.',
                        paste0('Number of integration sites recovered from earlier time points ($\\leq$ ', config$earlyVsLateCutoffDays, ' days).'),
                        paste0('Maximum estimated clonal abundance observered > ', config$earlyVsLateCutoffDays, ' days.'),
                        paste0('Maximum relative sample clonal abundance observered > ', config$earlyVsLateCutoffDays, ' days.'),
                        "Gene is found in a broad lists of oncogenes.",
                        "DEAL categories associated with gene."))

kable(tab, "latex", align="rl", linesep = "", booktabs=T, escape = F, col.names = NULL, caption = caption) %>%
  kable_styling(latex_options = c("hold_position"), font_size = 10)
```



```{r yyy, echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
caption <- ''
tab <- tibble(class = c('gene', 'totalSites', 'longitudinalSites', 'longitudinalSubjects', 'longitudinalTimePoints', 'latestTimePointDays', 'oncoGene', 'categories'),
              desc = c('Gene symbol.',
                       'Total number of unique integrations associated with gene.',  
                        paste0('Total number of unique integrations associated with gene recovered $\\geq$ ', 
                                           config$longitudinal_minTimeDays, ' days.'),  
                        paste0('Number of subjects associated with integrations associated with gene recovered $\\geq$ ', 
                                           config$longitudinal_minTimeDays, ' days.'), 
                        paste0('Number of time points sampled $\\geq$ ', 
                                           config$longitudinal_minTimeDays, ' days.'),
                        "Longest time point sampled.",
                        "Gene is found in a broad lists of oncogenes.",
                        "DEAL categories associated with gene."))

kable(tab, "latex", align="rl", linesep = "", booktabs=T, escape = F, col.names = NULL, caption = caption) %>%
  kable_styling(latex_options = c("hold_position"), font_size = 10)
```


